name: GitHub Pages Deploy

on:
  push:
    branches:
      - main  # Triggers the workflow when pushing to the 'main' branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Setup Ruby environment
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' # Specify the Ruby version you need for Jekyll
          bundler-cache: true

      # Install Jekyll and dependencies
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      # Build the Jekyll site
      - name: Build the site
        run: |
          bundle exec jekyll build

      # Deploy the site to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
